# Generated by Django 4.0.5 on 2022-06-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='BlogsCategoryModel',
        ),
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='BlogsModel',
        ),
        migrations.AlterModelOptions(
            name='blogscategorymodel',
            options={'verbose_name': 'категория блогов', 'verbose_name_plural': 'категории блогов'},
        ),
    ]
