# Generated by Django 4.0.5 on 2022-06-30 16:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorksCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'категория работ',
                'verbose_name_plural': 'категории работ',
            },
        ),
        migrations.CreateModel(
            name='WorksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('work_image', models.ImageField(upload_to='works/')),
                ('categories', models.ManyToManyField(to='works.workscategorymodel')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
            },
        ),
    ]
